/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_equipement (void)
{
  GtkWidget *equipement;
  GtkWidget *gen;
  GtkWidget *eg;
  GtkWidget *inaf;
  GtkWidget *treeaff;
  GtkWidget *actaff;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label5;
  GtkWidget *aff;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label4;
  GtkWidget *defec;
  GtkWidget *image3;
  GtkWidget *affich;
  GtkWidget *fixed3;
  GtkWidget *eajref;
  GtkWidget *eajn;
  GtkWidget *eajm;
  GtkObject *spinbuttonajaj_adj;
  GtkWidget *spinbuttonajaj;
  GtkObject *spinbuttonajaa_adj;
  GtkWidget *spinbuttonajaa;
  GtkObject *spinbuttonajmm_adj;
  GtkWidget *spinbuttonajmm;
  GtkObject *spinbuttonajmj_adj;
  GtkWidget *spinbuttonajmj;
  GtkObject *spinbuttonajma_adj;
  GtkWidget *spinbuttonajma;
  GtkWidget *label8;
  GtkWidget *label7;
  GtkWidget *label11;
  GtkWidget *label10;
  GtkWidget *label9;
  GtkWidget *refaj;
  GtkObject *spinbuttonajam_adj;
  GtkWidget *spinbuttonajam;
  GtkWidget *radiobuttonajed;
  GSList *radiobuttonajed_group = NULL;
  GtkWidget *radiobuttonajeb;
  GtkWidget *ajact;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label21;
  GtkWidget *ajaj;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label12;
  GtkWidget *aj;
  GtkWidget *fixed4;
  GtkWidget *emsref;
  GtkWidget *emsn;
  GtkWidget *emsm;
  GtkObject *spinbuttonmsaj_adj;
  GtkWidget *spinbuttonmsaj;
  GtkObject *spinbuttonmsaa_adj;
  GtkWidget *spinbuttonmsaa;
  GtkObject *spinbuttonmsmm_adj;
  GtkWidget *spinbuttonmsmm;
  GtkObject *spinbuttonmsmj_adj;
  GtkWidget *spinbuttonmsmj;
  GtkObject *spinbuttonmsma_adj;
  GtkWidget *spinbuttonmsma;
  GtkWidget *label13;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkObject *spinbuttonmsam_adj;
  GtkWidget *spinbuttonmsam;
  GtkWidget *label18;
  GtkWidget *emse;
  GtkWidget *label14;
  GtkWidget *label17;
  GtkWidget *mschr;
  GtkWidget *msmod;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label22;
  GtkWidget *mssup;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label23;
  GtkWidget *msact;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label20;
  GtkWidget *err;
  GtkWidget *modsup;

  equipement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (equipement), _("Equipements agricoles"));

  gen = gtk_fixed_new ();
  gtk_widget_show (gen);
  gtk_container_add (GTK_CONTAINER (equipement), gen);

  eg = gtk_notebook_new ();
  gtk_widget_show (eg);
  gtk_fixed_put (GTK_FIXED (gen), eg, 0, 0);
  gtk_widget_set_size_request (eg, 848, 624);

  inaf = gtk_fixed_new ();
  gtk_widget_show (inaf);
  gtk_container_add (GTK_CONTAINER (eg), inaf);

  treeaff = gtk_tree_view_new ();
  gtk_widget_show (treeaff);
  gtk_fixed_put (GTK_FIXED (inaf), treeaff, 32, 48);
  gtk_widget_set_size_request (treeaff, 780, 392);

  actaff = gtk_button_new ();
  gtk_widget_show (actaff);
  gtk_fixed_put (GTK_FIXED (inaf), actaff, 728, 520);
  gtk_widget_set_size_request (actaff, 96, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (actaff), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  aff = gtk_button_new ();
  gtk_widget_show (aff);
  gtk_fixed_put (GTK_FIXED (inaf), aff, 704, 8);
  gtk_widget_set_size_request (aff, 104, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (aff), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  defec = gtk_button_new ();
  gtk_widget_show (defec);
  gtk_fixed_put (GTK_FIXED (inaf), defec, 32, 464);
  gtk_widget_set_size_request (defec, 40, 40);
  gtk_container_set_border_width (GTK_CONTAINER (defec), 2);

  image3 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (defec), image3);

  affich = gtk_label_new (_("Affichage"));
  gtk_widget_show (affich);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (eg), gtk_notebook_get_nth_page (GTK_NOTEBOOK (eg), 0), affich);
  gtk_misc_set_padding (GTK_MISC (affich), 99, 8);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (eg), fixed3);

  eajref = gtk_entry_new ();
  gtk_widget_show (eajref);
  gtk_fixed_put (GTK_FIXED (fixed3), eajref, 320, 72);
  gtk_widget_set_size_request (eajref, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (eajref), 8226);

  eajn = gtk_entry_new ();
  gtk_widget_show (eajn);
  gtk_fixed_put (GTK_FIXED (fixed3), eajn, 320, 136);
  gtk_widget_set_size_request (eajn, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (eajn), 8226);

  eajm = gtk_entry_new ();
  gtk_widget_show (eajm);
  gtk_fixed_put (GTK_FIXED (fixed3), eajm, 320, 200);
  gtk_widget_set_size_request (eajm, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (eajm), 8226);

  spinbuttonajaj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonajaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonajaj_adj), 1, 0);
  gtk_widget_show (spinbuttonajaj);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonajaj, 320, 280);
  gtk_widget_set_size_request (spinbuttonajaj, 60, 27);

  spinbuttonajaa_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbuttonajaa = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonajaa_adj), 1, 0);
  gtk_widget_show (spinbuttonajaa);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonajaa, 464, 280);
  gtk_widget_set_size_request (spinbuttonajaa, 60, 27);

  spinbuttonajmm_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonajmm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonajmm_adj), 1, 0);
  gtk_widget_show (spinbuttonajmm);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonajmm, 392, 336);
  gtk_widget_set_size_request (spinbuttonajmm, 60, 27);

  spinbuttonajmj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonajmj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonajmj_adj), 1, 0);
  gtk_widget_show (spinbuttonajmj);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonajmj, 320, 336);
  gtk_widget_set_size_request (spinbuttonajmj, 60, 27);

  spinbuttonajma_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbuttonajma = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonajma_adj), 1, 0);
  gtk_widget_show (spinbuttonajma);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonajma, 464, 336);
  gtk_widget_set_size_request (spinbuttonajma, 60, 27);

  label8 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 208, 136);
  gtk_widget_set_size_request (label8, 105, 33);

  label7 = gtk_label_new (_("Marque:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 208, 200);
  gtk_widget_set_size_request (label7, 105, 33);

  label11 = gtk_label_new (_("Date d'achat:"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 208, 280);
  gtk_widget_set_size_request (label11, 105, 25);

  label10 = gtk_label_new (_("Date de maintenance:"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 144, 336);
  gtk_widget_set_size_request (label10, 169, 33);

  label9 = gtk_label_new (_("Etat:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 208, 416);
  gtk_widget_set_size_request (label9, 105, 25);

  refaj = gtk_label_new (_("Reference:"));
  gtk_widget_show (refaj);
  gtk_fixed_put (GTK_FIXED (fixed3), refaj, 216, 72);
  gtk_widget_set_size_request (refaj, 97, 33);

  spinbuttonajam_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonajam = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonajam_adj), 1, 0);
  gtk_widget_show (spinbuttonajam);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonajam, 392, 280);
  gtk_widget_set_size_request (spinbuttonajam, 60, 27);

  radiobuttonajed = gtk_radio_button_new_with_mnemonic (NULL, _("Defectueux"));
  gtk_widget_show (radiobuttonajed);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttonajed, 320, 416);
  gtk_widget_set_size_request (radiobuttonajed, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonajed), radiobuttonajed_group);
  radiobuttonajed_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonajed));

  radiobuttonajeb = gtk_radio_button_new_with_mnemonic (NULL, _("Bonne etat"));
  gtk_widget_show (radiobuttonajeb);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttonajeb, 456, 416);
  gtk_widget_set_size_request (radiobuttonajeb, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonajeb), radiobuttonajed_group);
  radiobuttonajed_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonajeb));

  ajact = gtk_button_new ();
  gtk_widget_show (ajact);
  gtk_fixed_put (GTK_FIXED (fixed3), ajact, 728, 520);
  gtk_widget_set_size_request (ajact, 96, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (ajact), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox6), label21, FALSE, FALSE, 0);

  ajaj = gtk_button_new ();
  gtk_widget_show (ajaj);
  gtk_fixed_put (GTK_FIXED (fixed3), ajaj, 352, 472);
  gtk_widget_set_size_request (ajaj, 114, 45);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ajaj), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 0);

  aj = gtk_label_new (_("Ajout"));
  gtk_widget_show (aj);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (eg), gtk_notebook_get_nth_page (GTK_NOTEBOOK (eg), 1), aj);
  gtk_misc_set_alignment (GTK_MISC (aj), 0.47, 0.5);
  gtk_misc_set_padding (GTK_MISC (aj), 107, 8);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (eg), fixed4);

  emsref = gtk_entry_new ();
  gtk_widget_show (emsref);
  gtk_fixed_put (GTK_FIXED (fixed4), emsref, 320, 32);
  gtk_widget_set_size_request (emsref, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (emsref), 8226);

  emsn = gtk_entry_new ();
  gtk_widget_show (emsn);
  gtk_fixed_put (GTK_FIXED (fixed4), emsn, 320, 136);
  gtk_widget_set_size_request (emsn, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (emsn), 8226);

  emsm = gtk_entry_new ();
  gtk_widget_show (emsm);
  gtk_fixed_put (GTK_FIXED (fixed4), emsm, 320, 208);
  gtk_widget_set_size_request (emsm, 160, 35);
  gtk_editable_set_editable (GTK_EDITABLE (emsm), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (emsm), 8226);

  spinbuttonmsaj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonmsaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmsaj_adj), 1, 0);
  gtk_widget_show (spinbuttonmsaj);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmsaj, 320, 280);
  gtk_widget_set_size_request (spinbuttonmsaj, 60, 27);

  spinbuttonmsaa_adj = gtk_adjustment_new (1, 2020, 2050, 1, 10, 10);
  spinbuttonmsaa = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmsaa_adj), 1, 0);
  gtk_widget_show (spinbuttonmsaa);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmsaa, 464, 280);
  gtk_widget_set_size_request (spinbuttonmsaa, 60, 27);

  spinbuttonmsmm_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmsmm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmsmm_adj), 1, 0);
  gtk_widget_show (spinbuttonmsmm);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmsmm, 392, 336);
  gtk_widget_set_size_request (spinbuttonmsmm, 60, 27);

  spinbuttonmsmj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonmsmj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmsmj_adj), 1, 0);
  gtk_widget_show (spinbuttonmsmj);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmsmj, 320, 336);
  gtk_widget_set_size_request (spinbuttonmsmj, 60, 27);

  spinbuttonmsma_adj = gtk_adjustment_new (2020, 2020, 2050, 1, 10, 10);
  spinbuttonmsma = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmsma_adj), 1, 0);
  gtk_widget_show (spinbuttonmsma);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmsma, 464, 336);
  gtk_widget_set_size_request (spinbuttonmsma, 60, 27);

  label13 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 208, 136);
  gtk_widget_set_size_request (label13, 105, 33);

  label15 = gtk_label_new (_("Date d'achat:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 208, 280);
  gtk_widget_set_size_request (label15, 105, 25);

  label16 = gtk_label_new (_("Date de maintenance:"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 144, 336);
  gtk_widget_set_size_request (label16, 169, 33);

  spinbuttonmsam_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmsam = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmsam_adj), 1, 0);
  gtk_widget_show (spinbuttonmsam);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmsam, 392, 280);
  gtk_widget_set_size_request (spinbuttonmsam, 60, 27);

  label18 = gtk_label_new (_("Reference:"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 216, 32);
  gtk_widget_set_size_request (label18, 97, 33);

  emse = gtk_entry_new ();
  gtk_widget_show (emse);
  gtk_fixed_put (GTK_FIXED (fixed4), emse, 320, 408);
  gtk_widget_set_size_request (emse, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (emse), 8226);

  label14 = gtk_label_new (_("Marque:"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 208, 208);
  gtk_widget_set_size_request (label14, 105, 33);

  label17 = gtk_label_new (_("Etat:"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 216, 408);
  gtk_widget_set_size_request (label17, 97, 33);

  mschr = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (mschr);
  gtk_fixed_put (GTK_FIXED (fixed4), mschr, 488, 32);
  gtk_widget_set_size_request (mschr, 104, 37);

  msmod = gtk_button_new ();
  gtk_widget_show (msmod);
  gtk_fixed_put (GTK_FIXED (fixed4), msmod, 304, 472);
  gtk_widget_set_size_request (msmod, 114, 45);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (msmod), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox7), label22, FALSE, FALSE, 0);

  mssup = gtk_button_new ();
  gtk_widget_show (mssup);
  gtk_fixed_put (GTK_FIXED (fixed4), mssup, 424, 472);
  gtk_widget_set_size_request (mssup, 122, 45);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (mssup), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox8), label23, FALSE, FALSE, 0);

  msact = gtk_button_new ();
  gtk_widget_show (msact);
  gtk_fixed_put (GTK_FIXED (fixed4), msact, 736, 512);
  gtk_widget_set_size_request (msact, 96, 37);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (msact), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox5), label20, FALSE, FALSE, 0);

  err = gtk_label_new ("");
  gtk_widget_show (err);
  gtk_fixed_put (GTK_FIXED (fixed4), err, 560, 488);
  gtk_widget_set_size_request (err, 208, 16);

  modsup = gtk_label_new (_("Modification/Suppression"));
  gtk_widget_show (modsup);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (eg), gtk_notebook_get_nth_page (GTK_NOTEBOOK (eg), 2), modsup);
  gtk_misc_set_padding (GTK_MISC (modsup), 60, 8);

  g_signal_connect ((gpointer) actaff, "clicked",
                    G_CALLBACK (on_actaff_clicked),
                    NULL);
  g_signal_connect ((gpointer) aff, "clicked",
                    G_CALLBACK (on_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) defec, "clicked",
                    G_CALLBACK (on_defec_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajact, "clicked",
                    G_CALLBACK (on_ajact_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajaj, "clicked",
                    G_CALLBACK (on_ajaj_clicked),
                    NULL);
  g_signal_connect ((gpointer) mschr, "clicked",
                    G_CALLBACK (on_mschr_clicked),
                    NULL);
  g_signal_connect ((gpointer) msmod, "clicked",
                    G_CALLBACK (on_msmod_clicked),
                    NULL);
  g_signal_connect ((gpointer) mssup, "clicked",
                    G_CALLBACK (on_mssup_clicked),
                    NULL);
  g_signal_connect ((gpointer) msact, "clicked",
                    G_CALLBACK (on_msact_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (equipement, equipement, "equipement");
  GLADE_HOOKUP_OBJECT (equipement, gen, "gen");
  GLADE_HOOKUP_OBJECT (equipement, eg, "eg");
  GLADE_HOOKUP_OBJECT (equipement, inaf, "inaf");
  GLADE_HOOKUP_OBJECT (equipement, treeaff, "treeaff");
  GLADE_HOOKUP_OBJECT (equipement, actaff, "actaff");
  GLADE_HOOKUP_OBJECT (equipement, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (equipement, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (equipement, image2, "image2");
  GLADE_HOOKUP_OBJECT (equipement, label5, "label5");
  GLADE_HOOKUP_OBJECT (equipement, aff, "aff");
  GLADE_HOOKUP_OBJECT (equipement, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (equipement, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (equipement, image1, "image1");
  GLADE_HOOKUP_OBJECT (equipement, label4, "label4");
  GLADE_HOOKUP_OBJECT (equipement, defec, "defec");
  GLADE_HOOKUP_OBJECT (equipement, image3, "image3");
  GLADE_HOOKUP_OBJECT (equipement, affich, "affich");
  GLADE_HOOKUP_OBJECT (equipement, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (equipement, eajref, "eajref");
  GLADE_HOOKUP_OBJECT (equipement, eajn, "eajn");
  GLADE_HOOKUP_OBJECT (equipement, eajm, "eajm");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonajaj, "spinbuttonajaj");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonajaa, "spinbuttonajaa");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonajmm, "spinbuttonajmm");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonajmj, "spinbuttonajmj");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonajma, "spinbuttonajma");
  GLADE_HOOKUP_OBJECT (equipement, label8, "label8");
  GLADE_HOOKUP_OBJECT (equipement, label7, "label7");
  GLADE_HOOKUP_OBJECT (equipement, label11, "label11");
  GLADE_HOOKUP_OBJECT (equipement, label10, "label10");
  GLADE_HOOKUP_OBJECT (equipement, label9, "label9");
  GLADE_HOOKUP_OBJECT (equipement, refaj, "refaj");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonajam, "spinbuttonajam");
  GLADE_HOOKUP_OBJECT (equipement, radiobuttonajed, "radiobuttonajed");
  GLADE_HOOKUP_OBJECT (equipement, radiobuttonajeb, "radiobuttonajeb");
  GLADE_HOOKUP_OBJECT (equipement, ajact, "ajact");
  GLADE_HOOKUP_OBJECT (equipement, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (equipement, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (equipement, image7, "image7");
  GLADE_HOOKUP_OBJECT (equipement, label21, "label21");
  GLADE_HOOKUP_OBJECT (equipement, ajaj, "ajaj");
  GLADE_HOOKUP_OBJECT (equipement, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (equipement, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (equipement, image4, "image4");
  GLADE_HOOKUP_OBJECT (equipement, label12, "label12");
  GLADE_HOOKUP_OBJECT (equipement, aj, "aj");
  GLADE_HOOKUP_OBJECT (equipement, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (equipement, emsref, "emsref");
  GLADE_HOOKUP_OBJECT (equipement, emsn, "emsn");
  GLADE_HOOKUP_OBJECT (equipement, emsm, "emsm");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonmsaj, "spinbuttonmsaj");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonmsaa, "spinbuttonmsaa");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonmsmm, "spinbuttonmsmm");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonmsmj, "spinbuttonmsmj");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonmsma, "spinbuttonmsma");
  GLADE_HOOKUP_OBJECT (equipement, label13, "label13");
  GLADE_HOOKUP_OBJECT (equipement, label15, "label15");
  GLADE_HOOKUP_OBJECT (equipement, label16, "label16");
  GLADE_HOOKUP_OBJECT (equipement, spinbuttonmsam, "spinbuttonmsam");
  GLADE_HOOKUP_OBJECT (equipement, label18, "label18");
  GLADE_HOOKUP_OBJECT (equipement, emse, "emse");
  GLADE_HOOKUP_OBJECT (equipement, label14, "label14");
  GLADE_HOOKUP_OBJECT (equipement, label17, "label17");
  GLADE_HOOKUP_OBJECT (equipement, mschr, "mschr");
  GLADE_HOOKUP_OBJECT (equipement, msmod, "msmod");
  GLADE_HOOKUP_OBJECT (equipement, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (equipement, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (equipement, image8, "image8");
  GLADE_HOOKUP_OBJECT (equipement, label22, "label22");
  GLADE_HOOKUP_OBJECT (equipement, mssup, "mssup");
  GLADE_HOOKUP_OBJECT (equipement, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (equipement, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (equipement, image9, "image9");
  GLADE_HOOKUP_OBJECT (equipement, label23, "label23");
  GLADE_HOOKUP_OBJECT (equipement, msact, "msact");
  GLADE_HOOKUP_OBJECT (equipement, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (equipement, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (equipement, image6, "image6");
  GLADE_HOOKUP_OBJECT (equipement, label20, "label20");
  GLADE_HOOKUP_OBJECT (equipement, err, "err");
  GLADE_HOOKUP_OBJECT (equipement, modsup, "modsup");

  return equipement;
}

