/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *Ajout_d_un_client;
  GtkWidget *image2;
  GtkWidget *entry1;
  GtkWidget *pr__nom;
  GtkWidget *entry2;
  GtkWidget *Num__ro_de_cin;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *sexe;
  GtkWidget *Date_de_naissance;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *Nom;
  GtkWidget *Num__ro_de_t__l__phone;
  GtkWidget *label18;
  GtkWidget *label17;
  GtkWidget *label16;
  GtkWidget *label15;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *button2_ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image3;
  GtkWidget *label14;
  GtkWidget *combobox1;
  GtkWidget *ajouter;
  GtkWidget *fixed3;
  GtkWidget *label20;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label23;
  GtkWidget *label22;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *image4;
  GtkWidget *treeview1;
  GtkWidget *image7;
  GtkWidget *label29;
  GtkWidget *label19;
  GtkWidget *button4_supp;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image6;
  GtkWidget *label28;
  GtkWidget *button3_modi;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image5;
  GtkWidget *label27;
  GtkWidget *checkbutton1_validmodif;
  GtkWidget *checkbutton2_validsupp;
  GtkWidget *label26;
  GtkWidget *combobox2;
  GtkWidget *afficher_supprimer_modifier;
  GtkWidget *fixed4;
  GtkWidget *label30;
  GtkWidget *entry8;
  GtkWidget *treeview2;
  GtkWidget *label34;
  GtkWidget *label32;
  GtkWidget *button5_chercher;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image8;
  GtkWidget *label31;
  GtkWidget *labelnomii;
  GtkWidget *chercher;
  GtkWidget *button6_quit;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image9;
  GtkWidget *label33;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 88);
  gtk_widget_set_size_request (notebook1, 752, 512);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  Ajout_d_un_client = gtk_label_new (_("Ajout d'un client"));
  gtk_widget_show (Ajout_d_un_client);
  gtk_fixed_put (GTK_FIXED (fixed2), Ajout_d_un_client, 200, 16);
  gtk_widget_set_size_request (Ajout_d_un_client, 152, 32);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed2), image2, 192, 24);
  gtk_widget_set_size_request (image2, 24, 16);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 96, 120);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  pr__nom = gtk_label_new (_("pr\303\251nom :"));
  gtk_widget_show (pr__nom);
  gtk_fixed_put (GTK_FIXED (fixed2), pr__nom, 8, 168);
  gtk_widget_set_size_request (pr__nom, 73, 16);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 96, 160);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  Num__ro_de_cin = gtk_label_new (_("Num\303\251ro de cin :"));
  gtk_widget_show (Num__ro_de_cin);
  gtk_fixed_put (GTK_FIXED (fixed2), Num__ro_de_cin, 0, 208);
  gtk_widget_set_size_request (Num__ro_de_cin, 113, 16);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 120, 200);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 184, 240);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  sexe = gtk_label_new (_("sexe :"));
  gtk_widget_show (sexe);
  gtk_fixed_put (GTK_FIXED (fixed2), sexe, 64, 288);
  gtk_widget_set_size_request (sexe, 41, 17);

  Date_de_naissance = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (Date_de_naissance);
  gtk_fixed_put (GTK_FIXED (fixed2), Date_de_naissance, 16, 336);
  gtk_widget_set_size_request (Date_de_naissance, 144, 16);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 168, 328);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2, 248, 328);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1950, 1950, 2050, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 328, 328);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  Nom = gtk_label_new (_("Nom :"));
  gtk_widget_show (Nom);
  gtk_fixed_put (GTK_FIXED (fixed2), Nom, 40, 128);
  gtk_widget_set_size_request (Nom, 41, 17);

  Num__ro_de_t__l__phone = gtk_label_new (_("Num\303\251ro de t\303\251l\303\251phone :"));
  gtk_widget_show (Num__ro_de_t__l__phone);
  gtk_fixed_put (GTK_FIXED (fixed2), Num__ro_de_t__l__phone, 8, 248);
  gtk_widget_set_size_request (Num__ro_de_t__l__phone, 168, 16);

  label18 = gtk_label_new (_("<span foreground=\"red\" ><b> Saisir num\303\251ro de t\303\251lephone !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 352, 240);
  gtk_widget_set_size_request (label18, 224, 25);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label17 = gtk_label_new (_("<span foreground=\"red\" ><b> Saisir num\303\251ro de cin !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 296, 200);
  gtk_widget_set_size_request (label17, 176, 25);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label16 = gtk_label_new (_("<span foreground=\"red\" ><b> Saisir pr\303\251nom !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 256, 160);
  gtk_widget_set_size_request (label16, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label15 = gtk_label_new (_("<span foreground=\"red\" ><b> Saisir nom !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 248, 120);
  gtk_widget_set_size_request (label15, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label12 = gtk_label_new (_("<span foreground=\"red\" ><b> client  existant !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 200, 48);
  gtk_widget_set_size_request (label12, 144, 24);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  label13 = gtk_label_new (_("<span foreground=\"green\" ><b> client ajout\303\251 avec succes !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 168, 72);
  gtk_widget_set_size_request (label13, 216, 24);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  button2_ajouter = gtk_button_new ();
  gtk_widget_show (button2_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_ajouter, 216, 368);
  gtk_widget_set_size_request (button2_ajouter, 120, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button2_ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox1), image3, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox1), label14, FALSE, FALSE, 0);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 128, 280);
  gtk_widget_set_size_request (combobox1, 128, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("femme"));

  ajouter = gtk_label_new (_("ajouter"));
  gtk_widget_show (ajouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), ajouter);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  label20 = gtk_label_new (_("pr\303\251nom :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 384, 112);
  gtk_widget_set_size_request (label20, 73, 16);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 472, 64);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 472, 104);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed3), entry7, 504, 144);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label23 = gtk_label_new (_("sexe :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 400, 192);
  gtk_widget_set_size_request (label23, 41, 17);

  label22 = gtk_label_new (_("Num\303\251ro de t\303\251l\303\251phone :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 328, 152);
  gtk_widget_set_size_request (label22, 168, 16);

  spinbutton4_adj = gtk_adjustment_new (1950, 1950, 2050, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton4, 616, 224);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton5, 552, 224);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton6, 488, 224);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label24 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 336, 232);
  gtk_widget_set_size_request (label24, 144, 16);

  label25 = gtk_label_new (_("Modification des donn\303\251es"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 464, 16);
  gtk_widget_set_size_request (label25, 192, 16);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed3), image4, 448, 16);
  gtk_widget_set_size_request (image4, 21, 21);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 16, 56);
  gtk_widget_set_size_request (treeview1, 312, 280);

  image7 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed3), image7, 104, 16);
  gtk_widget_set_size_request (image7, 24, 29);

  label29 = gtk_label_new (_("Les clients"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 112, 8);
  gtk_widget_set_size_request (label29, 112, 40);

  label19 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 408, 72);
  gtk_widget_set_size_request (label19, 41, 17);

  button4_supp = gtk_button_new ();
  gtk_widget_show (button4_supp);
  gtk_fixed_put (GTK_FIXED (fixed3), button4_supp, 168, 416);
  gtk_widget_set_size_request (button4_supp, 120, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button4_supp), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox3), image6, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox3), label28, FALSE, FALSE, 0);

  button3_modi = gtk_button_new ();
  gtk_widget_show (button3_modi);
  gtk_fixed_put (GTK_FIXED (fixed3), button3_modi, 504, 320);
  gtk_widget_set_size_request (button3_modi, 112, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button3_modi), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox2), image5, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox2), label27, FALSE, FALSE, 0);

  checkbutton1_validmodif = gtk_check_button_new_with_mnemonic (_("\303\252tes-vous s\303\273r de vouloir effectuer ces modifications"));
  gtk_widget_show (checkbutton1_validmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1_validmodif, 352, 272);
  gtk_widget_set_size_request (checkbutton1_validmodif, 376, 16);

  checkbutton2_validsupp = gtk_check_button_new_with_mnemonic (_("\303\252tes-vous s\303\273r de vouloir supprimer le client s\303\251lectionn\303\251e"));
  gtk_widget_show (checkbutton2_validsupp);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2_validsupp, 16, 368);
  gtk_widget_set_size_request (checkbutton2_validsupp, 408, 24);

  label26 = gtk_label_new (_("<span foreground=\"green\" ><b> client modifi\303\251 avec succes !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label26, 456, 40);
  gtk_widget_set_size_request (label26, 208, 16);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox2, 488, 184);
  gtk_widget_set_size_request (combobox2, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("femme"));

  afficher_supprimer_modifier = gtk_label_new (_("afficher/supprimer/modifier"));
  gtk_widget_show (afficher_supprimer_modifier);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), afficher_supprimer_modifier);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  label30 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 424, 96);
  gtk_widget_set_size_request (label30, 56, 24);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 488, 96);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview2, 48, 64);
  gtk_widget_set_size_request (treeview2, 328, 264);

  label34 = gtk_label_new ("");
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 416, 192);
  gtk_widget_set_size_request (label34, 81, 73);

  label32 = gtk_label_new (_("<span foreground=\"blue\" ><b> Resultat(s) obtenu(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 480, 216);
  gtk_widget_set_size_request (label32, 184, 24);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  button5_chercher = gtk_button_new ();
  gtk_widget_show (button5_chercher);
  gtk_fixed_put (GTK_FIXED (fixed4), button5_chercher, 512, 152);
  gtk_widget_set_size_request (button5_chercher, 112, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button5_chercher), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image8 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox4), image8, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox4), label31, FALSE, FALSE, 0);

  labelnomii = gtk_label_new (_("veuillez saisir un nom!"));
  gtk_fixed_put (GTK_FIXED (fixed4), labelnomii, 544, 48);
  gtk_widget_set_size_request (labelnomii, 49, 17);

  chercher = gtk_label_new (_("chercher"));
  gtk_widget_show (chercher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), chercher);

  button6_quit = gtk_button_new ();
  gtk_widget_show (button6_quit);
  gtk_fixed_put (GTK_FIXED (fixed1), button6_quit, 40, 24);
  gtk_widget_set_size_request (button6_quit, 104, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button6_quit), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image9 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox5), image9, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox5), label33, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button2_ajouter, "clicked",
                    G_CALLBACK (on_button2_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button4_supp, "clicked",
                    G_CALLBACK (on_button4_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_modi, "clicked",
                    G_CALLBACK (on_button3_modi_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1_validmodif, "toggled",
                    G_CALLBACK (on_checkbutton1_validmodif_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2_validsupp, "toggled",
                    G_CALLBACK (on_checkbutton2_validsupp_toggled),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button5_chercher, "clicked",
                    G_CALLBACK (on_button5_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6_quit, "clicked",
                    G_CALLBACK (on_button6_quit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, Ajout_d_un_client, "Ajout_d_un_client");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, pr__nom, "pr__nom");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, Num__ro_de_cin, "Num__ro_de_cin");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, sexe, "sexe");
  GLADE_HOOKUP_OBJECT (window1, Date_de_naissance, "Date_de_naissance");
  GLADE_HOOKUP_OBJECT (window1, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window1, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window1, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window1, Nom, "Nom");
  GLADE_HOOKUP_OBJECT (window1, Num__ro_de_t__l__phone, "Num__ro_de_t__l__phone");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, button2_ajouter, "button2_ajouter");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window1, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window1, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window1, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (window1, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (window1, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, button4_supp, "button4_supp");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, button3_modi, "button3_modi");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, checkbutton1_validmodif, "checkbutton1_validmodif");
  GLADE_HOOKUP_OBJECT (window1, checkbutton2_validsupp, "checkbutton2_validsupp");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (window1, afficher_supprimer_modifier, "afficher_supprimer_modifier");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window1, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, button5_chercher, "button5_chercher");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label31, "label31");
  GLADE_HOOKUP_OBJECT (window1, labelnomii, "labelnomii");
  GLADE_HOOKUP_OBJECT (window1, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (window1, button6_quit, "button6_quit");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed5;
  GtkWidget *tableau_de_bord_;
  GtkWidget *gclients;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window2), fixed5);

  tableau_de_bord_ = gtk_label_new (_("tableau de bord "));
  gtk_widget_show (tableau_de_bord_);
  gtk_fixed_put (GTK_FIXED (fixed5), tableau_de_bord_, 104, 8);
  gtk_widget_set_size_request (tableau_de_bord_, 184, 16);

  gclients = gtk_button_new_with_mnemonic (_("Gestion des clients "));
  gtk_widget_show (gclients);
  gtk_fixed_put (GTK_FIXED (fixed5), gclients, 88, 216);
  gtk_widget_set_size_request (gclients, 208, 45);

  g_signal_connect ((gpointer) gclients, "clicked",
                    G_CALLBACK (on_gclients_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window2, tableau_de_bord_, "tableau_de_bord_");
  GLADE_HOOKUP_OBJECT (window2, gclients, "gclients");

  return window2;
}

