/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_WindowDashboard (void)
{
  GtkWidget *WindowDashboard;
  GtkWidget *fixed2;
  GtkWidget *ButtonGestiondescapteurs;
  GtkWidget *ButtonGestiondesouvriers;
  GtkWidget *ButtonGestiondes__quipements;
  GtkWidget *ButtonGestiondesclients;
  GtkWidget *ButtonGestiondestroupeaux;
  GtkWidget *ButtonGestionducalendrier;

  WindowDashboard = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowDashboard), _("TABLE DE BORD"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (WindowDashboard), fixed2);

  ButtonGestiondescapteurs = gtk_button_new_with_mnemonic (_("Gestion des capteurs"));
  gtk_widget_show (ButtonGestiondescapteurs);
  gtk_fixed_put (GTK_FIXED (fixed2), ButtonGestiondescapteurs, 64, 8);
  gtk_widget_set_size_request (ButtonGestiondescapteurs, 184, 40);

  ButtonGestiondesouvriers = gtk_button_new_with_mnemonic (_("Gestion des ouvriers"));
  gtk_widget_show (ButtonGestiondesouvriers);
  gtk_fixed_put (GTK_FIXED (fixed2), ButtonGestiondesouvriers, 64, 56);
  gtk_widget_set_size_request (ButtonGestiondesouvriers, 184, 37);

  ButtonGestiondes__quipements = gtk_button_new_with_mnemonic (_("Gestion des \303\251quipements"));
  gtk_widget_show (ButtonGestiondes__quipements);
  gtk_fixed_put (GTK_FIXED (fixed2), ButtonGestiondes__quipements, 64, 104);
  gtk_widget_set_size_request (ButtonGestiondes__quipements, 184, 37);

  ButtonGestiondesclients = gtk_button_new_with_mnemonic (_("Gestion des clients"));
  gtk_widget_show (ButtonGestiondesclients);
  gtk_fixed_put (GTK_FIXED (fixed2), ButtonGestiondesclients, 64, 144);
  gtk_widget_set_size_request (ButtonGestiondesclients, 184, 37);

  ButtonGestiondestroupeaux = gtk_button_new_with_mnemonic (_("Gestion des troupeaux"));
  gtk_widget_show (ButtonGestiondestroupeaux);
  gtk_fixed_put (GTK_FIXED (fixed2), ButtonGestiondestroupeaux, 64, 192);
  gtk_widget_set_size_request (ButtonGestiondestroupeaux, 184, 32);

  ButtonGestionducalendrier = gtk_button_new_with_mnemonic (_("Gestion du calendrier"));
  gtk_widget_show (ButtonGestionducalendrier);
  gtk_fixed_put (GTK_FIXED (fixed2), ButtonGestionducalendrier, 64, 232);
  gtk_widget_set_size_request (ButtonGestionducalendrier, 184, 32);

  g_signal_connect ((gpointer) ButtonGestiondescapteurs, "clicked",
                    G_CALLBACK (on_ButtonGestiondescapteurs_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondesouvriers, "clicked",
                    G_CALLBACK (on_ButtonGestiondesouvriers_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondes__quipements, "clicked",
                    G_CALLBACK (on_ButtonGestiondes__quipements_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondesclients, "clicked",
                    G_CALLBACK (on_ButtonGestiondesclients_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestiondestroupeaux, "clicked",
                    G_CALLBACK (on_ButtonGestiondestroupeaux_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonGestionducalendrier, "clicked",
                    G_CALLBACK (on_ButtonGestionducalendrier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowDashboard, WindowDashboard, "WindowDashboard");
  GLADE_HOOKUP_OBJECT (WindowDashboard, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (WindowDashboard, ButtonGestiondescapteurs, "ButtonGestiondescapteurs");
  GLADE_HOOKUP_OBJECT (WindowDashboard, ButtonGestiondesouvriers, "ButtonGestiondesouvriers");
  GLADE_HOOKUP_OBJECT (WindowDashboard, ButtonGestiondes__quipements, "ButtonGestiondes__quipements");
  GLADE_HOOKUP_OBJECT (WindowDashboard, ButtonGestiondesclients, "ButtonGestiondesclients");
  GLADE_HOOKUP_OBJECT (WindowDashboard, ButtonGestiondestroupeaux, "ButtonGestiondestroupeaux");
  GLADE_HOOKUP_OBJECT (WindowDashboard, ButtonGestionducalendrier, "ButtonGestionducalendrier");

  return WindowDashboard;
}

GtkWidget*
create_WindowGestiondescapteurs (void)
{
  GtkWidget *WindowGestiondescapteurs;
  GtkWidget *fixed3;
  GtkWidget *LabelBienvenu;
  GtkWidget *ButtonQuit;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label14;
  GtkWidget *NotebookGestiondescapteurs;
  GtkWidget *fixed9;
  GtkWidget *EntryIdentifiant;
  GtkWidget *EntryMarque;
  GtkWidget *EntryPosition;
  GtkWidget *ImageAjout;
  GtkObject *spinbuttonetat_adj;
  GtkWidget *spinbuttonetat;
  GtkWidget *LabelMarque;
  GtkWidget *LabelPosition_;
  GtkWidget *LabelEtat;
  GtkWidget *ButtonAjouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label20;
  GtkObject *spinbuttonvaleur_adj;
  GtkWidget *spinbuttonvaleur;
  GtkWidget *LabelValeur;
  GtkWidget *LabelIdentifiant;
  GtkWidget *LabelAjouter;
  GtkWidget *label46;
  GtkWidget *labelid;
  GtkWidget *labelma;
  GtkWidget *labelpos;
  GtkWidget *labelverif;
  GtkWidget *labelfail;
  GtkWidget *labelsucess;
  GtkWidget *LabelType;
  GtkWidget *image33;
  GtkWidget *ComboBoxEntryType;
  GtkWidget *LabelAjout;
  GtkWidget *fixed7;
  GtkWidget *image17;
  GtkObject *spinbuttoneta_adj;
  GtkWidget *spinbuttoneta;
  GtkObject *spinbuttonval_adj;
  GtkWidget *spinbuttonval;
  GtkWidget *EntryPos1;
  GtkWidget *ImageSuppression;
  GtkWidget *ButtonSupprimer;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image12;
  GtkWidget *label34;
  GtkWidget *CheckButtonSupprimer;
  GtkWidget *image18;
  GtkWidget *LabelSupprimer;
  GtkWidget *treeview1;
  GtkWidget *label41;
  GtkWidget *LabelVal;
  GtkWidget *LabelEta1;
  GtkWidget *EntryMa1;
  GtkWidget *EntryId1;
  GtkWidget *label60;
  GtkWidget *LabelMa1;
  GtkWidget *label120;
  GtkWidget *ButtonModifier;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image31;
  GtkWidget *label116;
  GtkWidget *LabelTy1;
  GtkWidget *labelselection;
  GtkWidget *labelsucess1;
  GtkWidget *combobox2;
  GtkWidget *labelfail2;
  GtkWidget *LabelPos1;
  GtkWidget *labelsuccess2;
  GtkWidget *labelverif1;
  GtkWidget *checkbuttonmodif;
  GtkWidget *labelfail1;
  GtkWidget *ComboBoxEntryt1;
  GtkWidget *LabelSuppression;
  GtkWidget *fixed6;
  GtkWidget *EntryId2;
  GtkWidget *ImageRecherche;
  GtkWidget *LabelRechercher;
  GtkWidget *treeview2;
  GtkWidget *LabelId2;
  GtkWidget *ButtonRechercher;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image13;
  GtkWidget *label35;
  GtkWidget *labelsucess3;
  GtkWidget *labelfail3;
  GtkWidget *LabelRecherche;
  GtkWidget *fixed4;
  GtkWidget *TreeViewAffichageAlarmante;
  GtkWidget *ImageAffichageAlarmante;
  GtkWidget *LabelAffichageAlarmante;
  GtkWidget *ComboBoxAffichageAlarmante;
  GtkWidget *LabelListe;
  GtkWidget *fixed10;
  GtkWidget *treeview3;
  GtkWidget *image32;
  GtkWidget *label123;
  GtkWidget *label122;

  WindowGestiondescapteurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (WindowGestiondescapteurs), _("GESTION DES CAPTEURS"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (WindowGestiondescapteurs), fixed3);

  LabelBienvenu = gtk_label_new (_("BIENVENU(E) \303\200 L'OUTIL DE GESTION DES CAPTEURS"));
  gtk_widget_show (LabelBienvenu);
  gtk_fixed_put (GTK_FIXED (fixed3), LabelBienvenu, 168, 0);
  gtk_widget_set_size_request (LabelBienvenu, 392, 40);

  ButtonQuit = gtk_button_new ();
  gtk_widget_show (ButtonQuit);
  gtk_fixed_put (GTK_FIXED (fixed3), ButtonQuit, 720, 0);
  gtk_widget_set_size_request (ButtonQuit, 96, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ButtonQuit), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox3), label14, FALSE, FALSE, 0);

  NotebookGestiondescapteurs = gtk_notebook_new ();
  gtk_widget_show (NotebookGestiondescapteurs);
  gtk_fixed_put (GTK_FIXED (fixed3), NotebookGestiondescapteurs, 0, 32);
  gtk_widget_set_size_request (NotebookGestiondescapteurs, 848, 424);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (NotebookGestiondescapteurs), fixed9);

  EntryIdentifiant = gtk_entry_new ();
  gtk_widget_show (EntryIdentifiant);
  gtk_fixed_put (GTK_FIXED (fixed9), EntryIdentifiant, 256, 64);
  gtk_widget_set_size_request (EntryIdentifiant, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryIdentifiant), 8226);

  EntryMarque = gtk_entry_new ();
  gtk_widget_show (EntryMarque);
  gtk_fixed_put (GTK_FIXED (fixed9), EntryMarque, 256, 104);
  gtk_widget_set_size_request (EntryMarque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryMarque), 8226);

  EntryPosition = gtk_entry_new ();
  gtk_widget_show (EntryPosition);
  gtk_fixed_put (GTK_FIXED (fixed9), EntryPosition, 256, 144);
  gtk_widget_set_size_request (EntryPosition, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryPosition), 8226);

  ImageAjout = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ImageAjout);
  gtk_fixed_put (GTK_FIXED (fixed9), ImageAjout, 232, 21);
  gtk_widget_set_size_request (ImageAjout, 16, 16);

  spinbuttonetat_adj = gtk_adjustment_new (0, 0, 1, 1, 10, 10);
  spinbuttonetat = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonetat_adj), 1, 0);
  gtk_widget_show (spinbuttonetat);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonetat, 264, 256);
  gtk_widget_set_size_request (spinbuttonetat, 60, 27);

  LabelMarque = gtk_label_new (_("Marque :"));
  gtk_widget_show (LabelMarque);
  gtk_fixed_put (GTK_FIXED (fixed9), LabelMarque, 144, 104);
  gtk_widget_set_size_request (LabelMarque, 120, 25);

  LabelPosition_ = gtk_label_new (_("Position :"));
  gtk_widget_show (LabelPosition_);
  gtk_fixed_put (GTK_FIXED (fixed9), LabelPosition_, 144, 144);
  gtk_widget_set_size_request (LabelPosition_, 120, 25);

  LabelEtat = gtk_label_new (_("\303\211tat : "));
  gtk_widget_show (LabelEtat);
  gtk_fixed_put (GTK_FIXED (fixed9), LabelEtat, 152, 256);
  gtk_widget_set_size_request (LabelEtat, 120, 25);

  ButtonAjouter = gtk_button_new ();
  gtk_widget_show (ButtonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed9), ButtonAjouter, 552, 272);
  gtk_widget_set_size_request (ButtonAjouter, 112, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ButtonAjouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox4), label20, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label20, 70, 30);

  spinbuttonvaleur_adj = gtk_adjustment_new (1, 0, 200, 1, 10, 10);
  spinbuttonvaleur = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonvaleur_adj), 1, 0);
  gtk_widget_show (spinbuttonvaleur);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbuttonvaleur, 264, 224);
  gtk_widget_set_size_request (spinbuttonvaleur, 60, 27);

  LabelValeur = gtk_label_new (_("Valeur :"));
  gtk_widget_show (LabelValeur);
  gtk_fixed_put (GTK_FIXED (fixed9), LabelValeur, 152, 224);
  gtk_widget_set_size_request (LabelValeur, 105, 25);

  LabelIdentifiant = gtk_label_new (_("Identifiant : "));
  gtk_widget_show (LabelIdentifiant);
  gtk_fixed_put (GTK_FIXED (fixed9), LabelIdentifiant, 136, 64);
  gtk_widget_set_size_request (LabelIdentifiant, 128, 24);

  LabelAjouter = gtk_label_new (_("AJOUT D'UN CAPTEUR"));
  gtk_widget_show (LabelAjouter);
  gtk_fixed_put (GTK_FIXED (fixed9), LabelAjouter, 200, 0);
  gtk_widget_set_size_request (LabelAjouter, 264, 56);

  label46 = gtk_label_new (_("0: en panne, 1: en marche"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed9), label46, 344, 256);
  gtk_widget_set_size_request (label46, 184, 25);

  labelid = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez saisir l'identifiant </b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelid, 416, 64);
  gtk_widget_set_size_request (labelid, 192, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelid), TRUE);

  labelma = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez saisir la marque </b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelma, 416, 104);
  gtk_widget_set_size_request (labelma, 192, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelma), TRUE);

  labelpos = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez saisir la position </b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelpos, 416, 144);
  gtk_widget_set_size_request (labelpos, 192, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelpos), TRUE);

  labelverif = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Saisir des donn\303\251es convenables !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelverif, 472, 224);
  gtk_widget_set_size_request (labelverif, 312, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelverif), TRUE);

  labelfail = gtk_label_new (_("<span foreground=\"red\"><i>Capteur existe d\303\251j\303\240! Veuillez saisir un autre !</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelfail, 448, 168);
  gtk_widget_set_size_request (labelfail, 360, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelfail), TRUE);

  labelsucess = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\"><i>Capteur ajout\303\251 avec succ\303\250s !</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), labelsucess, 504, 200);
  gtk_widget_set_size_request (labelsucess, 224, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelsucess), TRUE);

  LabelType = gtk_label_new (_("Type :"));
  gtk_widget_show (LabelType);
  gtk_fixed_put (GTK_FIXED (fixed9), LabelType, 128, 184);
  gtk_widget_set_size_request (LabelType, 128, 25);

  image33 = create_pixmap (WindowGestiondescapteurs, "capteur.png");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed9), image33, 616, 16);
  gtk_widget_set_size_request (image33, 216, 144);

  ComboBoxEntryType = gtk_combo_box_entry_new_text ();
  gtk_widget_show (ComboBoxEntryType);
  gtk_fixed_put (GTK_FIXED (fixed9), ComboBoxEntryType, 256, 184);
  gtk_widget_set_size_request (ComboBoxEntryType, 157, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryType), _("Humidit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryType), _("Temp\303\251rature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryType), _("Plantes "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryType), _("Arbres"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryType), _("Bovins"));

  LabelAjout = gtk_label_new (_("Ajouter"));
  gtk_widget_show (LabelAjout);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (NotebookGestiondescapteurs), gtk_notebook_get_nth_page (GTK_NOTEBOOK (NotebookGestiondescapteurs), 0), LabelAjout);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (NotebookGestiondescapteurs), fixed7);

  image17 = gtk_image_new_from_icon_name ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed7), image17, 72, 24);
  gtk_widget_set_size_request (image17, 16, 16);

  spinbuttoneta_adj = gtk_adjustment_new (0, 0, 1, 1, 10, 10);
  spinbuttoneta = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttoneta_adj), 1, 0);
  gtk_widget_show (spinbuttoneta);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttoneta, 768, 216);
  gtk_widget_set_size_request (spinbuttoneta, 48, 24);

  spinbuttonval_adj = gtk_adjustment_new (1, 0, 200, 1, 10, 10);
  spinbuttonval = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonval_adj), 1, 0);
  gtk_widget_show (spinbuttonval);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbuttonval, 768, 184);
  gtk_widget_set_size_request (spinbuttonval, 48, 25);

  EntryPos1 = gtk_entry_new ();
  gtk_widget_show (EntryPos1);
  gtk_fixed_put (GTK_FIXED (fixed7), EntryPos1, 488, 208);
  gtk_widget_set_size_request (EntryPos1, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryPos1), 8226);

  ImageSuppression = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ImageSuppression);
  gtk_fixed_put (GTK_FIXED (fixed7), ImageSuppression, 504, 8);
  gtk_widget_set_size_request (ImageSuppression, 16, 16);

  ButtonSupprimer = gtk_button_new ();
  gtk_widget_show (ButtonSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed7), ButtonSupprimer, 688, 32);
  gtk_widget_set_size_request (ButtonSupprimer, 120, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ButtonSupprimer), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox7), image12, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox7), label34, FALSE, FALSE, 0);

  CheckButtonSupprimer = gtk_check_button_new_with_mnemonic (_("Voulez-vous vraiment supprimer ce capteur ?"));
  gtk_widget_show (CheckButtonSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed7), CheckButtonSupprimer, 352, 32);
  gtk_widget_set_size_request (CheckButtonSupprimer, 352, 32);

  image18 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed7), image18, 520, 112);
  gtk_widget_set_size_request (image18, 16, 16);

  LabelSupprimer = gtk_label_new (_("SUPPRESSION D'UN CAPTEUR"));
  gtk_widget_show (LabelSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed7), LabelSupprimer, 520, 0);
  gtk_widget_set_size_request (LabelSupprimer, 208, 32);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview1, 8, 56);
  gtk_widget_set_size_request (treeview1, 328, 256);

  label41 = gtk_label_new (_("AFFICHAGE DES CAPTEURS"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed7), label41, 0, 0);
  gtk_widget_set_size_request (label41, 368, 64);

  LabelVal = gtk_label_new (_("Valeur :"));
  gtk_widget_show (LabelVal);
  gtk_fixed_put (GTK_FIXED (fixed7), LabelVal, 688, 184);
  gtk_widget_set_size_request (LabelVal, 88, 25);

  LabelEta1 = gtk_label_new (_("\303\211tat :"));
  gtk_widget_show (LabelEta1);
  gtk_fixed_put (GTK_FIXED (fixed7), LabelEta1, 680, 216);
  gtk_widget_set_size_request (LabelEta1, 89, 24);

  EntryMa1 = gtk_entry_new ();
  gtk_widget_show (EntryMa1);
  gtk_fixed_put (GTK_FIXED (fixed7), EntryMa1, 488, 176);
  gtk_widget_set_size_request (EntryMa1, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryMa1), 8226);

  EntryId1 = gtk_entry_new ();
  gtk_widget_show (EntryId1);
  gtk_fixed_put (GTK_FIXED (fixed7), EntryId1, 488, 144);
  gtk_widget_set_size_request (EntryId1, 136, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryId1), 8226);

  label60 = gtk_label_new (_("MODIFICATION D'UN CAPTEUR"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed7), label60, 512, 104);
  gtk_widget_set_size_request (label60, 264, 32);

  LabelMa1 = gtk_label_new (_("Marque : "));
  gtk_widget_show (LabelMa1);
  gtk_fixed_put (GTK_FIXED (fixed7), LabelMa1, 368, 176);
  gtk_widget_set_size_request (LabelMa1, 128, 24);

  label120 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed7), label120, 352, 144);
  gtk_widget_set_size_request (label120, 136, 25);

  ButtonModifier = gtk_button_new ();
  gtk_widget_show (ButtonModifier);
  gtk_fixed_put (GTK_FIXED (fixed7), ButtonModifier, 704, 264);
  gtk_widget_set_size_request (ButtonModifier, 112, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (ButtonModifier), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image31 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox14), image31, FALSE, FALSE, 0);

  label116 = gtk_label_new_with_mnemonic (_("Modifier "));
  gtk_widget_show (label116);
  gtk_box_pack_start (GTK_BOX (hbox14), label116, FALSE, FALSE, 0);

  LabelTy1 = gtk_label_new (_("Type  :"));
  gtk_widget_show (LabelTy1);
  gtk_fixed_put (GTK_FIXED (fixed7), LabelTy1, 608, 144);
  gtk_widget_set_size_request (LabelTy1, 112, 24);

  labelselection = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez s\303\251lectionner une ligne \303\240 modifier !</b></span>\n"));
  gtk_fixed_put (GTK_FIXED (fixed7), labelselection, 344, 304);
  gtk_widget_set_size_request (labelselection, 336, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelselection), TRUE);

  labelsucess1 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Capteur bien supprim\303\251 !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), labelsucess1, 640, 56);
  gtk_widget_set_size_request (labelsucess1, 208, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelsucess1), TRUE);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox2, 336, 72);
  gtk_widget_set_size_request (combobox2, 24, 23);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), "");

  labelfail2 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Capteur d\303\251j\303\240 existant!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), labelfail2, 656, 280);
  gtk_widget_set_size_request (labelfail2, 216, 41);
  gtk_label_set_use_markup (GTK_LABEL (labelfail2), TRUE);

  LabelPos1 = gtk_label_new (_("Position : "));
  gtk_widget_show (LabelPos1);
  gtk_fixed_put (GTK_FIXED (fixed7), LabelPos1, 392, 176);
  gtk_widget_set_size_request (LabelPos1, 72, 81);

  labelsuccess2 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Capteur bien modifi\303\251!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), labelsuccess2, 520, 288);
  gtk_widget_set_size_request (labelsuccess2, 200, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelsuccess2), TRUE);
  gtk_label_set_justify (GTK_LABEL (labelsuccess2), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (labelsuccess2), TRUE);

  labelverif1 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Saisir des donn\303\251es convenables !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), labelverif1, 344, 256);
  gtk_widget_set_size_request (labelverif1, 288, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelverif1), TRUE);

  checkbuttonmodif = gtk_check_button_new_with_mnemonic (_("Voulez-vous vraiment modifier ce capteur ?"));
  gtk_widget_show (checkbuttonmodif);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbuttonmodif, 504, 240);
  gtk_widget_set_size_request (checkbuttonmodif, 328, 24);

  labelfail1 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Capteur non supprim\303\251! Veuilllez s\303\251lectionner une ligne!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), labelfail1, 392, 80);
  gtk_widget_set_size_request (labelfail1, 464, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelfail1), TRUE);

  ComboBoxEntryt1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (ComboBoxEntryt1);
  gtk_fixed_put (GTK_FIXED (fixed7), ComboBoxEntryt1, 696, 144);
  gtk_widget_set_size_request (ComboBoxEntryt1, 157, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryt1), _("Humidit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryt1), _("Temp\303\251rature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryt1), _("Plantes "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryt1), _("Arbres"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxEntryt1), _("Bovins"));

  LabelSuppression = gtk_label_new (_("Afficher/Supprimer/Modifier"));
  gtk_widget_show (LabelSuppression);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (NotebookGestiondescapteurs), gtk_notebook_get_nth_page (GTK_NOTEBOOK (NotebookGestiondescapteurs), 1), LabelSuppression);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (NotebookGestiondescapteurs), fixed6);

  EntryId2 = gtk_entry_new ();
  gtk_widget_show (EntryId2);
  gtk_fixed_put (GTK_FIXED (fixed6), EntryId2, 472, 104);
  gtk_widget_set_size_request (EntryId2, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (EntryId2), 8226);

  ImageRecherche = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ImageRecherche);
  gtk_fixed_put (GTK_FIXED (fixed6), ImageRecherche, 288, 24);
  gtk_widget_set_size_request (ImageRecherche, 16, 16);

  LabelRechercher = gtk_label_new (_("RECHERCHE D'UN CAPTEUR "));
  gtk_widget_show (LabelRechercher);
  gtk_fixed_put (GTK_FIXED (fixed6), LabelRechercher, 208, 0);
  gtk_widget_set_size_request (LabelRechercher, 392, 64);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview2, 24, 56);
  gtk_widget_set_size_request (treeview2, 324, 240);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview2), TRUE);

  LabelId2 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (LabelId2);
  gtk_fixed_put (GTK_FIXED (fixed6), LabelId2, 336, 104);
  gtk_widget_set_size_request (LabelId2, 160, 24);

  ButtonRechercher = gtk_button_new ();
  gtk_widget_show (ButtonRechercher);
  gtk_fixed_put (GTK_FIXED (fixed6), ButtonRechercher, 664, 104);
  gtk_widget_set_size_request (ButtonRechercher, 136, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (ButtonRechercher), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image13 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox8), image13, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Rechercher "));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox8), label35, FALSE, FALSE, 0);

  labelsucess3 = gtk_label_new_with_mnemonic (_("<span foreground=\"orange\"><b>Si le capteur existe, il apparait sinon il n'apparait pas!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), labelsucess3, 408, 144);
  gtk_widget_set_size_request (labelsucess3, 392, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelsucess3), TRUE);

  labelfail3 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Veuillez saisir l'identifiant du capteur \303\240 chercher</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), labelfail3, 456, 160);
  gtk_widget_set_size_request (labelfail3, 384, 41);
  gtk_label_set_use_markup (GTK_LABEL (labelfail3), TRUE);

  LabelRecherche = gtk_label_new (_("Rechercher"));
  gtk_widget_show (LabelRecherche);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (NotebookGestiondescapteurs), gtk_notebook_get_nth_page (GTK_NOTEBOOK (NotebookGestiondescapteurs), 2), LabelRecherche);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (NotebookGestiondescapteurs), fixed4);

  TreeViewAffichageAlarmante = gtk_tree_view_new ();
  gtk_widget_show (TreeViewAffichageAlarmante);
  gtk_fixed_put (GTK_FIXED (fixed4), TreeViewAffichageAlarmante, 280, 64);
  gtk_widget_set_size_request (TreeViewAffichageAlarmante, 408, 256);

  ImageAffichageAlarmante = gtk_image_new_from_icon_name ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ImageAffichageAlarmante);
  gtk_fixed_put (GTK_FIXED (fixed4), ImageAffichageAlarmante, 288, 24);
  gtk_widget_set_size_request (ImageAffichageAlarmante, 16, 16);

  LabelAffichageAlarmante = gtk_label_new (_("AFFICHAGE DES CAPTEURS \303\200 VALEURS ALARMANTES"));
  gtk_widget_show (LabelAffichageAlarmante);
  gtk_fixed_put (GTK_FIXED (fixed4), LabelAffichageAlarmante, 296, 0);
  gtk_widget_set_size_request (LabelAffichageAlarmante, 392, 64);

  ComboBoxAffichageAlarmante = gtk_combo_box_new_text ();
  gtk_widget_show (ComboBoxAffichageAlarmante);
  gtk_fixed_put (GTK_FIXED (fixed4), ComboBoxAffichageAlarmante, 688, 88);
  gtk_widget_set_size_request (ComboBoxAffichageAlarmante, 24, 23);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxAffichageAlarmante), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxAffichageAlarmante), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxAffichageAlarmante), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxAffichageAlarmante), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxAffichageAlarmante), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxAffichageAlarmante), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxAffichageAlarmante), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxAffichageAlarmante), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (ComboBoxAffichageAlarmante), "");

  LabelListe = gtk_label_new (_("Liste des capteurs \303\240 valeurs alarmantes"));
  gtk_widget_show (LabelListe);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (NotebookGestiondescapteurs), gtk_notebook_get_nth_page (GTK_NOTEBOOK (NotebookGestiondescapteurs), 3), LabelListe);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (NotebookGestiondescapteurs), fixed10);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview3, 256, 64);
  gtk_widget_set_size_request (treeview3, 460, 248);

  image32 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed10), image32, 320, 32);
  gtk_widget_set_size_request (image32, 32, 21);

  label123 = gtk_label_new (_("AFFICHAGE DES CAPTEURS D\303\211FECTUEUX "));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed10), label123, 328, 24);
  gtk_widget_set_size_request (label123, 320, 33);

  label122 = gtk_label_new (_("Liste des capteurs d\303\251fectueux "));
  gtk_widget_show (label122);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (NotebookGestiondescapteurs), gtk_notebook_get_nth_page (GTK_NOTEBOOK (NotebookGestiondescapteurs), 4), label122);

  g_signal_connect ((gpointer) ButtonQuit, "clicked",
                    G_CALLBACK (on_ButtonQuit_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonAjouter, "clicked",
                    G_CALLBACK (on_ButtonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) ButtonSupprimer, "clicked",
                    G_CALLBACK (on_ButtonSupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ButtonModifier, "clicked",
                    G_CALLBACK (on_ButtonModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ButtonRechercher, "clicked",
                    G_CALLBACK (on_ButtonRechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) TreeViewAffichageAlarmante, "row_activated",
                    G_CALLBACK (on_TreeViewAffichageAlarmante_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview3, "row_activated",
                    G_CALLBACK (on_treeview3_row_activated),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (labelsuccess2), ButtonModifier);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (WindowGestiondescapteurs, WindowGestiondescapteurs, "WindowGestiondescapteurs");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelBienvenu, "LabelBienvenu");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ButtonQuit, "ButtonQuit");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, image3, "image3");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label14, "label14");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, NotebookGestiondescapteurs, "NotebookGestiondescapteurs");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, EntryIdentifiant, "EntryIdentifiant");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, EntryMarque, "EntryMarque");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, EntryPosition, "EntryPosition");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ImageAjout, "ImageAjout");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, spinbuttonetat, "spinbuttonetat");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelMarque, "LabelMarque");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelPosition_, "LabelPosition_");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelEtat, "LabelEtat");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ButtonAjouter, "ButtonAjouter");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, image5, "image5");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label20, "label20");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, spinbuttonvaleur, "spinbuttonvaleur");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelValeur, "LabelValeur");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelIdentifiant, "LabelIdentifiant");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelAjouter, "LabelAjouter");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label46, "label46");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelid, "labelid");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelma, "labelma");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelpos, "labelpos");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelverif, "labelverif");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelfail, "labelfail");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelsucess, "labelsucess");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelType, "LabelType");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, image33, "image33");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ComboBoxEntryType, "ComboBoxEntryType");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelAjout, "LabelAjout");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, image17, "image17");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, spinbuttoneta, "spinbuttoneta");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, spinbuttonval, "spinbuttonval");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, EntryPos1, "EntryPos1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ImageSuppression, "ImageSuppression");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ButtonSupprimer, "ButtonSupprimer");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, image12, "image12");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label34, "label34");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, CheckButtonSupprimer, "CheckButtonSupprimer");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, image18, "image18");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelSupprimer, "LabelSupprimer");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label41, "label41");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelVal, "LabelVal");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelEta1, "LabelEta1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, EntryMa1, "EntryMa1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, EntryId1, "EntryId1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label60, "label60");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelMa1, "LabelMa1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label120, "label120");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ButtonModifier, "ButtonModifier");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, image31, "image31");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label116, "label116");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelTy1, "LabelTy1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelselection, "labelselection");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelsucess1, "labelsucess1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelfail2, "labelfail2");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelPos1, "LabelPos1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelsuccess2, "labelsuccess2");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelverif1, "labelverif1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, checkbuttonmodif, "checkbuttonmodif");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelfail1, "labelfail1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ComboBoxEntryt1, "ComboBoxEntryt1");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelSuppression, "LabelSuppression");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, EntryId2, "EntryId2");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ImageRecherche, "ImageRecherche");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelRechercher, "LabelRechercher");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelId2, "LabelId2");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ButtonRechercher, "ButtonRechercher");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, image13, "image13");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label35, "label35");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelsucess3, "labelsucess3");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, labelfail3, "labelfail3");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelRecherche, "LabelRecherche");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, TreeViewAffichageAlarmante, "TreeViewAffichageAlarmante");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ImageAffichageAlarmante, "ImageAffichageAlarmante");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelAffichageAlarmante, "LabelAffichageAlarmante");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, ComboBoxAffichageAlarmante, "ComboBoxAffichageAlarmante");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, LabelListe, "LabelListe");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, image32, "image32");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label123, "label123");
  GLADE_HOOKUP_OBJECT (WindowGestiondescapteurs, label122, "label122");

  return WindowGestiondescapteurs;
}

